openapi: 3.0.0
info:
  title: E-Commerce API
  description: API for managing Users, Products, Carts, and Orders.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
  
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
        password:
          type: string
          writeOnly: true
        salt:
          type: string
    
    Address:
      type: object
      required:
        - line_one
        - city
        - postcode
        - country
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
        type:
          type: string
          default: shipping
        line_one:
          type: string
        line_two:
          type: string
        city:
          type: string
        postcode:
          type: string
        country:
          type: string

    Product:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        price:
          type: number
          format: double
        description:
          type: string
        stock:
          type: integer

    Order:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
        status:
          type: string
          enum: 
            - pending
            - active
            - shipped
            - delivered
        created_at:
          type: string
          format: date-time
    
    Cart:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time

paths:
  # -------------------------
  # AUTH ROUTES
  # -------------------------
  /signup:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '302':
          description: Redirects to index.html on success
        '500':
          description: Server error

  /login:
    post:
      tags:
        - Auth
      summary: Log in via Password (Passport Local)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '302':
          description: Redirects to /loggedIn.html on success, /index.html on failure

  /logout:
    post:
      tags:
        - Auth
      summary: Log out the current user
      responses:
        '302':
          description: Redirects to /

  /me:
    get:
      tags:
        - Auth
      summary: Get current logged-in user details
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Current user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
        '401':
          description: Not logged in

  # -------------------------
  # USER ROUTES
  # -------------------------
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - Users
      summary: Create a user (Admin/Direct route)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                hashed_password:
                  type: string
                salt:
                  type: string
      responses:
        '201':
          description: User created
  
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: User ID
    get:
      tags:
        - Users
      summary: Get user by ID
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - Users
      summary: Update a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User modified
    delete:
      tags:
        - Users
      summary: Delete a user
      responses:
        '200':
          description: User deleted

  /users/address:
    post:
      tags:
        - Users
      summary: Add an address to a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address'
      responses:
        '201':
          description: Address added

  # -------------------------
  # PRODUCT ROUTES
  # -------------------------
  /products:
    get:
      tags:
        - Products
      summary: Get all products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - Products
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product added

  /products/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
    get:
      tags:
        - Products
      summary: Get product by ID
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      tags:
        - Products
      summary: Update product details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                description:
                  type: string
                stock:
                  type: integer
      responses:
        '200':
          description: Product modified
    delete:
      tags:
        - Products
      summary: Delete a product
      responses:
        '200':
          description: Product deleted
        '404':
          description: Product not found

  # -------------------------
  # ORDER ROUTES
  # -------------------------
  /orders:
    get:
      tags:
        - Orders
      summary: Get all orders
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: integer
                status:
                  type: string
                  default: pending
      responses:
        '201':
          description: Order added

  /orders/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Order ID
    get:
      tags:
        - Orders
      summary: Get order by ID
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
    put:
      tags:
        - Orders
      summary: Update item quantity in an order
      description: Updates the quantity of a specific product within the order. If quantity is 0, item is removed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - product_id
                - quantity
              properties:
                product_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '200':
          description: Order modified or product removed
        '404':
          description: Item not in order or order does not exist
    delete:
      tags:
        - Orders
      summary: Delete an order
      responses:
        '200':
          description: Order deleted
        '404':
          description: Order not found

  /orders/items/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Order ID
    get:
      tags:
        - Orders
      summary: Get items and total price for an order
      responses:
        '200':
          description: Items and total
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: integer
                        quantity:
                          type: integer
                  total:
                    type: number
        '404':
          description: Order not found

  /orders/status/{status}:
    parameters:
      - in: path
        name: status
        schema:
          type: string
        required: true
    get:
      tags:
        - Orders
      summary: Get orders by status
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: No orders found

  /orders/addItem:
    post:
      tags:
        - Orders
      summary: Add a product to an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - order_id
                - product_id
              properties:
                order_id:
                  type: integer
                product_id:
                  type: integer
                quantity:
                  type: integer
                  default: 1
      responses:
        '201':
          description: Item added

  # -------------------------
  # CART ROUTES
  # -------------------------
  /carts:
    get:
      tags:
        - Carts
      summary: Get all carts
      responses:
        '200':
          description: List of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
    post:
      tags:
        - Carts
      summary: Create a new cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
      responses:
        '201':
          description: Cart created

  /carts/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      tags:
        - Carts
      summary: Get cart by ID
      responses:
        '200':
          description: Cart details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    put:
      tags:
        - Carts
      summary: Update cart details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Cart updated
    delete:
      tags:
        - Carts
      summary: Delete a cart
      responses:
        '200':
          description: Cart deleted

  /carts/items/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      tags:
        - Carts
      summary: Get items in a specific cart
      responses:
        '200':
          description: List of cart items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    quantity:
                      type: integer

  /carts/status/{status}:
    parameters:
      - in: path
        name: status
        required: true
        schema:
          type: string
    get:
      tags:
        - Carts
      summary: Get carts by status
      responses:
        '200':
          description: List of carts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'

  /carts/addItem:
    post:
      tags:
        - Carts
      summary: Add item to cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_id:
                  type: integer
                product_id:
                  type: integer
                quantity:
                  type: integer
      responses:
        '201':
          description: Item added

  /carts/order:
    post:
      tags:
        - Carts
      summary: Convert Cart to Order (Checkout)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_id:
                  type: integer
      responses:
        '201':
          description: Order created from cart